kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-jenkins
  namespace: jenkins
spec:
  #storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/root/jen" #node path